export const tableroBase1 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroBase2 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroBase3 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroHijo1 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroHijo2 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroMutacion1 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];
export const tableroMutacion2 = [
    [
        { col: '1', row: '8', queen: 0},
        { col: '1', row: '7', queen: 0},
        { col: '1', row: '6', queen: 0},
        { col: '1', row: '5', queen: 0},
        { col: '1', row: '4', queen: 0},
        { col: '1', row: '3', queen: 0},
        { col: '1', row: '2', queen: 0},
        { col: '1', row: '1', queen: 0},
    ],
    [
        { col: '2', row: '8', queen: 0},
        { col: '2', row: '7', queen: 0},
        { col: '2', row: '6', queen: 0},
        { col: '2', row: '5', queen: 0},
        { col: '2', row: '4', queen: 0},
        { col: '2', row: '3', queen: 0},
        { col: '2', row: '2', queen: 0},
        { col: '2', row: '1', queen: 0},
    ],
    [
        { col: '3', row: '8', queen: 0},
        { col: '3', row: '7', queen: 0},
        { col: '3', row: '6', queen: 0},
        { col: '3', row: '5', queen: 0},
        { col: '3', row: '4', queen: 0},
        { col: '3', row: '3', queen: 0},
        { col: '3', row: '2', queen: 0},
        { col: '3', row: '1', queen: 0},
    ],
    [
        { col: '4', row: '8', queen: 0},
        { col: '4', row: '7', queen: 0},
        { col: '4', row: '6', queen: 0},
        { col: '4', row: '5', queen: 0},
        { col: '4', row: '4', queen: 0},
        { col: '4', row: '3', queen: 0},
        { col: '4', row: '2', queen: 0},
        { col: '4', row: '1', queen: 0},
    ],
    [
        { col: '5', row: '8', queen: 0},
        { col: '5', row: '7', queen: 0},
        { col: '5', row: '6', queen: 0},
        { col: '5', row: '5', queen: 0},
        { col: '5', row: '4', queen: 0},
        { col: '5', row: '3', queen: 0},
        { col: '5', row: '2', queen: 0},
        { col: '5', row: '1', queen: 0},
    ],
    [
        { col: '6', row: '8', queen: 0},
        { col: '6', row: '7', queen: 0},
        { col: '6', row: '6', queen: 0},
        { col: '6', row: '5', queen: 0},
        { col: '6', row: '4', queen: 0},
        { col: '6', row: '3', queen: 0},
        { col: '6', row: '2', queen: 0},
        { col: '6', row: '1', queen: 0},
    ],
    [
        { col: '7', row: '8', queen: 0},
        { col: '7', row: '7', queen: 0},
        { col: '7', row: '6', queen: 0},
        { col: '7', row: '5', queen: 0},
        { col: '7', row: '4', queen: 0},
        { col: '7', row: '3', queen: 0},
        { col: '7', row: '2', queen: 0},
        { col: '7', row: '1', queen: 0},
    ],
    [
        { col: '8', row: '8', queen: 0},
        { col: '8', row: '7', queen: 0},
        { col: '8', row: '6', queen: 0},
        { col: '8', row: '5', queen: 0},
        { col: '8', row: '4', queen: 0},
        { col: '8', row: '3', queen: 0},
        { col: '8', row: '2', queen: 0},
        { col: '8', row: '1', queen: 0},
    ],
];